#!/bin/bash

# This is jethalal ki duniya

<< comment
Anything written
here will not be execute
comment

name="Babitaji"

echo "Name is $name, and date is $(date)"

echo "enter the name:"

read username

echo "you entered $username"


